### ISSUE TITLE
Error report.  

### ISSUE THREAD

**Issue by stacybri** [worldbank/GEPD#10]
Kanika, 

I am getting an error when I reach the learning_poverty.R part of the country report code.  Can you look into this error?  See below.

> lp_figure <-   learning_poverty_df %>%
+   ggplot(aes(x=grx, y= tab)) +
+   geom_point(pch = 21, aes(fill= grx), size = 2) +
+   scale_fill_gradient(low = "grey21", high = "grey100") +
+   geom_point(data = learning_poverty_df[learning_poverty_df$ID == country_label,], aes(x = grx, y=tab), 
+              pch=21, color = "black", fill = "#ffffb3", size = 3.5) +
+   geom_point(data = learning_poverty_df[learning_poverty_df$ID == region_label,], aes(x = grx, y=tab), 
+              pch=21, color = "black", fill = "#0066ff", size = 3.5) +
+   geom_point(data = learning_poverty_df[learning_poverty_df$ID == income_label,], aes(x = grx, y=tab), 
+              pch=21, color = "black", fill = "#ff9933", size = 3.5) +
+   #scale_x_continuous(breaks = c(0,0.25,0.5,0.75,1), labels = percent) +
+   geom_text_repel(data = subset(learning_poverty_df, !is.na(ID)), aes(x = grx, y = tab, label = iso3c, color = iso3c), 
+                   fontface = 'bold', size = 3.5, box.padding = 2, segment.color = 'black', ylim = c(0,0.1), force = 1) +
+   scale_colour_manual(values = c("#282828", "#0066ff", "#ff9933")) +
+   ylim(-0.1,0.1)+
+   annotate("text", x = c(0,0.25,0.5,0.75,1), y = -0.06, label = c("0%", "25%", "50%", "75%", "100%")) +
+   theme_void() +
+   theme(legend.position = "none")
> ggsave(here("LP figures", paste("lp_figure_", country_file_name, ".png", sep = '')), height = 1.5, width = 5)
Error in grDevices::png(..., res = dpi, units = "in") : 
  unable to start png() device
In addition: Warning messages:
1: In grDevices::png(..., res = dpi, units = "in") :
  unable to open file 'C:/Users/wb469649/OneDrive - WBG/Documents/Github/GEPD/Country_Reports/LP figures/lp_figure_JOR.png' for writing
2: In grDevices::png(..., res = dpi, units = "in") : opening device failed
> 

https://github.com/worldbank/GEPD/blob/db5a3fe42d4664afc0aae0b960970a187a82d5b0/Country_Reports/Code/learning_poverty.R#L63

**Comment by KV1990** [comment]
This seems to be a file path issue. A new folder called 'LP figures' needs to be created in the gepd>Country_reports branch. The learning poverty figures get saved in 'LP figures'. I can add a new file anywhere but I am not seeing an option to create a new folder myself.
